name: delete
on:
  release:
    types: [published]
    inputs:
      delete-old-releases:
        description: 'Remove old releases'  

jobs:
  del_runs:
    runs-on: ubuntu-latest
    name: delete-old-releases
    steps:
      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 7
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
